<?php

/**
 * @file
 * Contains dialogflow_rules.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\dialogflow_rules\Event\DialogFlowWebhookEvent;
use Drupal\api_ai_webhook\ApiAiEvent;

/**
 * Implements hook_help().
 */
function dialogflow_rules_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the dialogflow_rules module.
    case 'help.page.dialogflow_rules':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Dialogflow Rules integration') . '</p>';
      return $output;

    default:
  }
}


/**
 * Implements hook_trigger_info().
 */
function dialogflow_rules_trigger_info() {
  return array(
    'Chatbot' => array(
      'dialogflow_rules_webhook' => array(
        'label' => t('When a chatbot triggers a webhook.'),
      ),
    ),
  );
}
