<?php

/**
 * @file
 * Contains dialogflow_rules.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\dialogflow_rules\Event\DialogFlowWebhookEvent;
use Drupal\api_ai_webhook\ApiAiEvent;

/**
 * Implements hook_help().
 */
function dialogflow_rules_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the dialogflow_rules module.
    case 'help.page.dialogflow_rules':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Dialogflow Rules integration') . '</p>';
      return $output;

    default:
  }
}


/**
 * Implements hook_trigger_info().
 */
function dialogflow_rules_trigger_info() {
  return array(
    'Chatbot' => array(
      'dialogflow_rules_webhook' => array(
        'label' => t('When a chatbot triggers a webhook.'),
      ),
    ),
  );
}




/**
 * Implements hook_entity_view().
 */
// function dialogflow_rules_entity_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
//   // Only handle content entities and ignore config entities.
//   if ($event instanceof ApiAiEvent) {
//     $event = new DialogFlowWebhookEvent($logger_entry, ['logger_entry' => $logger_entry]);
//     $event_dispatcher = \Drupal::service('event_dispatcher');
//     $event_dispatcher->dispatch("Dialogflow:$action", $event);
//   }
// }
