<?php

/**
 * @file
 * Contains helloworld_intent.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function dialogflow_example_intent_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the helloworld_intent module.
    case 'help.page.dialogflow_example_intent':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Chatbot API - Implementation example') . '</p>';
      return $output;

    default:
  }
}
